[
  {
    id: 1,
    company_name: 'Tech Innovators Inc.',
    revenue: 1200000,
    url: 'http://techinnovators.com',
    last_entry_date: '2023-01-15',
    active_status: true,
  },
  {
    id: 2,
    company_name: 'Future Solutions Ltd.',
    revenue: 850000,
    url: 'http://futuresolutions.com',
    last_entry_date: '2023-01-20',
    active_status: false,
  },
  {
    id: 3,
    company_name: 'Creative Minds LLC',
    revenue: 950000,
    url: 'http://creativeminds.com',
    last_entry_date: '2023-02-05',
    active_status: true,
  },
  {
    id: 4,
    company_name: 'NextGen Technologies',
    revenue: 1500000,
    url: 'http://nextgentech.com',
    last_entry_date: '2023-02-10',
    active_status: true,
  },
  {
    id: 5,
    company_name: 'Innovative Solutions',
    revenue: 700000,
    url: 'http://innovativesolutions.com',
    last_entry_date: '2023-02-15',
    active_status: false,
  },
  {
    id: 6,
    company_name: 'Global Tech Corp.',
    revenue: 2000000,
    url: 'http://globaltech.com',
    last_entry_date: '2023-03-01',
    active_status: true,
  },
  {
    id: 7,
    company_name: 'Smart Systems',
    revenue: 1100000,
    url: 'http://smartsystems.com',
    last_entry_date: '2023-03-05',
    active_status: true,
  },
  {
    id: 8,
    company_name: 'Tech Pioneers',
    revenue: 950000,
    url: 'http://techpioneers.com',
    last_entry_date: '2023-03-10',
    active_status: false,
  },
  {
    id: 9,
    company_name: 'Visionary Solutions',
    revenue: 1250000,
    url: 'http://visionarysolutions.com',
    last_entry_date: '2023-03-15',
    active_status: true,
  },
  {
    id: 10,
    company_name: 'Advanced Tech',
    revenue: 1750000,
    url: 'http://advancedtech.com',
    last_entry_date: '2023-03-20',
    active_status: true,
  },
  {
    id: 11,
    company_name: 'Tech Innovators Inc.',
    revenue: 1200000,
    url: 'http://techinnovators.com',
    last_entry_date: '2023-04-01',
    active_status: false,
  },
  {
    id: 12,
    company_name: 'Future Solutions Ltd.',
    revenue: 850000,
    url: 'http://futuresolutions.com',
    last_entry_date: '2023-04-05',
    active_status: true,
  },
  {
    id: 13,
    company_name: 'Creative Minds LLC',
    revenue: 950000,
    url: 'http://creativeminds.com',
    last_entry_date: '2023-04-10',
    active_status: false,
  },
  {
    id: 14,
    company_name: 'NextGen Technologies',
    revenue: 1500000,
    url: 'http://nextgentech.com',
    last_entry_date: '2023-04-15',
    active_status: true,
  },
  {
    id: 15,
    company_name: 'Innovative Solutions',
    revenue: 700000,
    url: 'http://innovativesolutions.com',
    last_entry_date: '2023-04-20',
    active_status: true,
  },
  {
    id: 16,
    company_name: 'Global Tech Corp.',
    revenue: 2000000,
    url: 'http://globaltech.com',
    last_entry_date: '2023-05-01',
    active_status: false,
  },
  {
    id: 17,
    company_name: 'Smart Systems',
    revenue: 1100000,
    url: 'http://smartsystems.com',
    last_entry_date: '2023-05-05',
    active_status: true,
  },
  {
    id: 18,
    company_name: 'Tech Pioneers',
    revenue: 950000,
    url: 'http://techpioneers.com',
    last_entry_date: '2023-05-10',
    active_status: false,
  },
  {
    id: 19,
    company_name: 'Visionary Solutions',
    revenue: 1250000,
    url: 'http://visionarysolutions.com',
    last_entry_date: '2023-05-15',
    active_status: true,
  },
  {
    id: 20,
    company_name: 'Advanced Tech',
    revenue: 1750000,
    url: 'http://advancedtech.com',
    last_entry_date: '2023-05-20',
    active_status: true,
  },
];
